esphome:
  name: a1

#esp32:
#  board: esp32-s2-saola-1
#  framework:
#    type: esp-idf

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    platform_version: 4.4.0


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A1 Fallback Hotspot"
    password: !secret fallback_password
    ap_timeout: 10min

mdns:
  disabled: false

time:
  - platform: homeassistant
    id: homeassistant_time


#captive_portal:

i2c:
  sda: 13
  scl: 16
  scan: true
  id: bus_a

sensor:
  - platform: uptime
    name: Uptime Sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: tof10120
    name: "TOF10120 Distance"
    update_interval: 1s

light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO15

button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results
  - platform: version
    name: "ESPHome Version"
